version: "3.9"

services:
  db:
    profiles: ['dev']
    image: postgres:14
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    profiles: ['build']
    build: ../
    env_file:
      - ../production.env
    ports: 
      - "8173:80"

volumes:
  db_data:

networks:
  default:
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
